# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from your repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Azure using Azure Login Action
    - name: Azure Login
      uses: azure/login@v1.6.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 4: Set up Helm
    - name: Setup Helm
      uses: azure/setup-helm@v1.1

    # Step 5: Run Terraform to create resources in Azure
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
