name: Destroy Infrastructure

on:
  workflow_dispatch: # Enables manual triggering through GitHub Actions UI

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Azure Login
      uses: azure/login@v1.6.1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}
        
    - name: Set up Kubernetes Context for AKS
      uses: azure/aks-set-context@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: example-resources  
          cluster-name: example-aks1
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
