# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Step 2: Log in to Azure using Azure Login Action
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
         creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Set up Kubernetes Context for AKS
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: example-resources  
          cluster-name: example-aks1
          
      - name: Retrieve Elasticsearch External IP
        run: |
          ELASTICSEARCH_IP=$(kubectl get service elasticsearch-master -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Elasticsearch External IP: $ELASTICSEARCH_IP"
          echo "ELASTICSEARCH_IP=$ELASTICSEARCH_IP" >> $GITHUB_ENV

      # - name: Update Logstash Configuration with Elasticsearch IP
      #   run: |
      #     cd elk-stack/logstash
      #     sed -i "22s/.*/  hosts: ['${{ env.ELASTICSEARCH_IP }}:9200']/" values.yaml
      #     sed -i "46s/.*/  hosts: ['${{ env.ELASTICSEARCH_IP }}:9200']/" values.yaml
      - name: Update Logstash Configuration with Elasticsearch IP
        run: |
          cd elk-stack/logstash
          # Update line 22 with the new IP
          sed -i "s|xpack.monitoring.elasticsearch.hosts: \[.*\]|xpack.monitoring.elasticsearch.hosts: [ \"https://${{ env.ELASTICSEARCH_IP }}:9200\" ]|" values.yaml
          # Update line 46 with the new IP
          sed -i "s|hosts => \[.*\]|hosts => [\"https://${{ env.ELASTICSEARCH_IP }}:9200\"]|" values.yaml


      - name: Update Dependencies for Logstash
        run: |
          cd elk-stack/logstash
          helm dependency update

      - name: Install Logstash
        run: |
          cd elk-stack/logstash
          helm install logstash ./
